namespace Pennington.Markdown.Extensions.Tabs;

/// <summary>
/// Maps language identifiers to human-readable display names for tab headers.
/// </summary>
internal static class LanguageNormalizer
{
    public static string GetLanguageName(string? input)
    {
        if (string.IsNullOrWhiteSpace(input))
            return "Text";

        var colonLocation = input.IndexOf(':');
        if (colonLocation > -1)
        {
            input = input[..colonLocation];
        }

        return LanguageMap.GetValueOrDefault(input, input);
    }

    private static readonly Dictionary<string, string> LanguageMap = new(StringComparer.OrdinalIgnoreCase)
    {
        { "gbnf", "GBNF" },
        // .NET Languages
        { "csharp", "C#" },
        { "c#", "C#" },
        { "cs", "C#" },
        { "c-sharp", "C#" },
        { "vb", "Visual Basic .NET" },
        { "vbnet", "Visual Basic .NET" },
        { "visualbasic", "Visual Basic .NET" },
        { "vb.net", "Visual Basic .NET" },
        { "fsharp", "F#" },
        { "f#", "F#" },
        { "fs", "F#" },
        { "nemerle", "Nemerle" },
        { "ironpython", "IronPython" },
        { "ironruby", "IronRuby" },
        { "powershell", "PowerShell" },
        { "posh", "PowerShell" },
        { "pwsh", "PowerShell" },
        { "razor", "Razor" },
        { "cshtml", "Razor" },
        { "aspx", "ASP.NET" },
        { "aspx-vb", "ASP.NET" },
        { "asp.net", "ASP.NET" },
        { "blazor", "Blazor" },
        { "xaml", "XAML" },
        { "axml", "XAML" },

        // Web Technologies
        { "html", "HTML" },
        { "htm", "HTML" },
        { "xhtml", "HTML" },
        { "css", "CSS" },
        { "js", "JavaScript" },
        { "javascript", "JavaScript" },
        { "ecmascript", "JavaScript" },
        { "jsx", "JavaScript" },
        { "ts", "TypeScript" },
        { "typescript", "TypeScript" },
        { "tsx", "TypeScript" },
        { "json", "JSON" },
        { "jsonc", "JSON with Comments" },
        { "json5", "JSON5" },
        { "vue", "Vue" },
        { "svelte", "Svelte" },
        { "php", "PHP" },
        { "webassembly", "WebAssembly" },
        { "wasm", "WebAssembly" },
        { "graphql", "GraphQL" },
        { "gql", "GraphQL" },
        { "less", "Less" },
        { "sass", "Sass" },
        { "scss", "SCSS" },
        { "stylus", "Stylus" },
        { "styl", "Stylus" },
        { "coffeescript", "CoffeeScript" },
        { "coffee", "CoffeeScript" },
        { "htaccess", "ApacheConf" },
        { "apacheconf", "ApacheConf" },
        { "apache", "ApacheConf" },
        { "mdx", "MDX" },
        { "handlebars", "Handlebars" },
        { "hbs", "Handlebars" },
        { "mustache", "Mustache" },
        { "pug", "Pug" },
        { "jade", "Pug" },
        { "ejs", "EJS" },

        // Markup & Documentation
        { "md", "Markdown" },
        { "markdown", "Markdown" },
        { "mdown", "Markdown" },
        { "mkd", "Markdown" },
        { "mkdn", "Markdown" },
        { "rmd", "RMarkdown" },
        { "rst", "reStructuredText" },
        { "rest", "reStructuredText" },
        { "asciidoc", "AsciiDoc" },
        { "adoc", "AsciiDoc" },
        { "asc", "AsciiDoc" },
        { "tex", "TeX" },
        { "latex", "TeX" },
        { "wiki", "Wikitext" },
        { "mediawiki", "Wikitext" },
        { "wikitext", "Wikitext" },
        { "creole", "Creole" },
        { "org", "Org" },
        { "txt", "Text" },
        { "text", "Text" },

        // C/C++ Family
        { "c", "C" },
        { "h", "C" },
        { "cpp", "C++" },
        { "c++", "C++" },
        { "cc", "C++" },
        { "cxx", "C++" },
        { "hpp", "C++" },
        { "hxx", "C++" },
        { "h++", "C++" },
        { "c++11", "C++" },
        { "c++14", "C++" },
        { "c++17", "C++" },
        { "c++20", "C++" },
        { "c++23", "C++" },
        { "cplusplus", "C++" },
        { "c--", "C--" },
        { "cminus", "C--" },
        { "objectivec", "Objective-C" },
        { "obj-c", "Objective-C" },
        { "objc", "Objective-C" },
        { "objectivecpp", "Objective-C++" },
        { "obj-c++", "Objective-C++" },
        { "objc++", "Objective-C++" },
        { "cuda", "Cuda" },
        { "opencl", "OpenCL" },

        // Other Systems Languages
        { "rust", "Rust" },
        { "rs", "Rust" },
        { "go", "Go" },
        { "golang", "Go" },
        { "d", "D" },
        { "dlang", "D" },
        { "zig", "Zig" },
        { "pascal", "Pascal" },
        { "delphi", "Pascal" },
        { "objectpascal", "Pascal" },
        { "ada", "Ada" },
        { "fortran", "Fortran" },
        { "cobol", "COBOL" },
        { "swift", "Swift" },
        { "kotlin", "Kotlin" },
        { "nim", "Nim" },
        { "v", "V" },
        { "vlang", "V" },
        { "odin", "Odin" },
        { "jai", "JAI" },

        // JVM Languages
        { "java", "Java" },
        { "groovy", "Groovy" },
        { "scala", "Scala" },
        { "clojure", "Clojure" },
        { "clj", "Clojure" },
        { "jython", "Jython" },

        // Scripting Languages
        { "python", "Python" },
        { "py", "Python" },
        { "py3", "Python" },
        { "python3", "Python" },
        { "ruby", "Ruby" },
        { "rb", "Ruby" },
        { "perl", "Perl" },
        { "pl", "Perl" },
        { "lua", "Lua" },
        { "r", "R" },
        { "julia", "Julia" },
        { "tcl", "Tcl" },
        { "haskell", "Haskell" },
        { "hs", "Haskell" },
        { "erlang", "Erlang" },
        { "erl", "Erlang" },
        { "elixir", "Elixir" },
        { "ex", "Elixir" },
        { "exs", "Elixir" },
        { "ocaml", "OCaml" },
        { "ml", "OCaml" },
        { "reason", "Reason" },
        { "racket", "Racket" },
        { "rkt", "Racket" },

        // Shell/OS
        { "shell", "Shell" },
        { "sh", "Shell" },
        { "bash", "Shell" },
        { "zsh", "Shell" },
        { "fish", "fish" },
        { "cmd", "Batchfile" },
        { "bat", "Batchfile" },
        { "batch", "Batchfile" },
        { "batchfile", "Batchfile" },
        { "ps1", "PowerShell" },
        { "psm1", "PowerShell" },
        { "psd1", "PowerShell" },

        // Data/Config
        { "yaml", "YAML" },
        { "yml", "YAML" },
        { "toml", "TOML" },
        { "ini", "INI" },
        { "cfg", "INI" },
        { "conf", "INI" },
        { "config", "INI" },
        { "xml", "XML" },
        { "xsd", "XML" },
        { "rss", "XML" },
        { "wsdl", "XML" },
        { "xslt", "XSLT" },
        { "xsl", "XSLT" },
        { "svg", "SVG" },
        { "csv", "CSV" },
        { "tsv", "TSV" },
        { "sql", "SQL" },
        { "plsql", "PLSQL" },
        { "tsql", "TSQL" },
        { "mysql", "SQL" },
        { "pgsql", "PLpgSQL" },
        { "postgresql", "PLpgSQL" },
        { "sqlite", "SQL" },
        { "properties", "Java Properties" },
        { "prop", "Java Properties" },
        { "dotenv", "Dotenv" },
        { "env", "Dotenv" },
        { "editorconfig", "EditorConfig" },
        { "gitignore", ".gitignore" },
        { "dockerignore", ".dockerignore" },
        { "npmignore", ".npmignore" },
        { "gitattributes", ".gitattributes" },
        { "dockerfile", ".dockerfile" },
        { "jenkinsfile", "Groovy" },
        { "csproj", "csproj" },
        { "vbproj", "vbproj" },
        { "fsproj", "fsproj" },
        { "vcxproj", "vcxproj" },
        { "proj", "proj" },
        { "sln", "sln" },

        // Game Development
        { "hlsl", "HLSL" },
        { "glsl", "GLSL" },
        { "shader", "ShaderLab" },
        { "cg", "HLSL" },
        { "unity", "Unity3D Asset" },
        { "unity3d", "Unity3D Asset" },
        { "unreal", "UnrealScript" },
        { "unrealscript", "UnrealScript" },
        { "godot", "Godot Resource" },
        { "gdscript", "GDScript" },

        // Mobile Development
        { "dart", "Dart" },
        { "flutter", "Dart" },
        { "reactnative", "JavaScript" },

        // Other Common Languages
        { "assembly", "Assembly" },
        { "asm", "Assembly" },
        { "nasm", "Assembly" },
        { "lisp", "Common Lisp" },
        { "scheme", "Scheme" },
        { "prolog", "Prolog" },
        { "basic", "BASIC" },
        { "vba", "VBA" },
        { "matlab", "MATLAB" },
        { "mathematica", "Mathematica" },
        { "wolfram", "Mathematica" },
        { "actionscript", "ActionScript" },
        { "as3", "ActionScript" },
        { "applescript", "AppleScript" },
        { "autohotkey", "AutoHotkey" },
        { "ahk", "AutoHotkey" },
        { "autoit", "AutoIt" },
        { "au3", "AutoIt" },
        { "awk", "Awk" },
        { "mawk", "Awk" },
        { "gawk", "Awk" },

        // Blockchain/Web3
        { "solidity", "Solidity" },
        { "sol", "Solidity" },
        { "vyper", "Vyper" },
        { "vy", "Vyper" },
        { "move", "Move" },
        { "cairo", "Cairo" },
        { "clarity", "Clarity" },
        { "cadence", "Cadence" },

        // Others
        { "regex", "Regular Expression" },
        { "regexp", "Regular Expression" },
        { "diff", "Diff" },
        { "patch", "Diff" },
        { "cmake", "CMake" },
        { "makefile", "Makefile" },
        { "make", "Makefile" },
        { "mf", "Makefile" },
        { "dot", "Graphviz (DOT)" },
        { "graphviz", "Graphviz (DOT)" },
        { "ebnf", "EBNF" },
        { "abnf", "ABNF" },
        { "bnf", "ABNF" },
        { "bibtex", "BibTeX" },
        { "bib", "BibTeX" },
        { "proto", "Protocol Buffer" },
        { "protobuf", "Protocol Buffer" },
        { "thrift", "Thrift" },
    };
}